export default {
  name: 'Aarush',
  palette: {
    skin: '#B5825A',
    hair: '#0A0A0A',
    eye: '#3A2510',
    outfit1: '#0F0F12',      // black Nike hoodie
    outfit2: '#0A0A0A',      // black cargo pants
    shoes: '#0F0F12',        // black Dunks
    shoesAccent: '#F5F5F5',
    undertop: '#F0F0F0',
    chain: '#C8C8C8',
    accent: '#FFFFFF',       // Nike swoosh
    aura: '#9B59B6',
  },
  features: {
    hairStyle: 'short_neat',
    hoodieStyle: 'pullover',
    hasUndershirt: true,
    hasPantChain: true,
    hasHoodieLogo: true,
    hasEarrings: false,
    hasChain: false,
    hasGlasses: true,
    hasBandana: false,
    hasNoseRing: false,
    shoeStyle: 'nike_dunk',
  },
  proportions: { weight: 90, height: 1.0, width: 0.97 },
  stats: { speed: 1.0, jump: 1.0, air: 1.1, fall: 0.95 },
  moves: {
    neutralLight: {
      name: 'Frame Poke',
      startup: 3, active: 3, recovery: 7,
      damage: 5,
      knockback: { base: 8, scaling: 0.3, angle: 40 },
      hitstun: 11, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 18, y: -62, w: 28, h: 18 }],
    },
    sideLight: {
      name: 'Yeezy Kick',
      startup: 4, active: 5, recovery: 9,
      damage: 8,
      knockback: { base: 16, scaling: 0.55, angle: 28 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 12, y: -42, w: 38, h: 24 }],
    },
    upLight: {
      name: 'Specs Tilt',
      startup: 4, active: 6, recovery: 8,
      damage: 8,
      knockback: { base: 20, scaling: 0.66, angle: 82 },
      hitstun: 14, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: -10, y: -90, w: 30, h: 28 }],
    },
    downLight: {
      name: 'Jogger Sweep',
      startup: 5, active: 4, recovery: 9,
      damage: 6,
      knockback: { base: 11, scaling: 0.44, angle: 270 },
      hitstun: 12, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 10, y: -12, w: 32, h: 12 }],
    },
    neutralAir: {
      name: 'Hover Kick',
      startup: 4, active: 8, recovery: 10,
      damage: 8,
      knockback: { base: 14, scaling: 0.5, angle: 48 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -18, y: -58, w: 42, h: 38 }],
    },
    forwardAir: {
      name: 'Lens Strike',
      startup: 5, active: 5, recovery: 8,
      damage: 10,
      knockback: { base: 21, scaling: 0.67, angle: 28 },
      hitstun: 15, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: 20, y: -56, w: 34, h: 22 }],
    },
    backAir: {
      name: 'Pivot Kick',
      startup: 6, active: 5, recovery: 9,
      damage: 11,
      knockback: { base: 24, scaling: 0.73, angle: 148 },
      hitstun: 17, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -32, y: -46, w: 28, h: 20 }],
    },
    upAir: {
      name: 'Logic Flip',
      startup: 4, active: 6, recovery: 8,
      damage: 9,
      knockback: { base: 20, scaling: 0.65, angle: 87 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -10, y: -96, w: 24, h: 20 }],
    },
    downAir: {
      name: 'Code Drop',
      startup: 8, active: 5, recovery: 11,
      damage: 13,
      knockback: { base: 16, scaling: 0.76, angle: 270 },
      hitstun: 13, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: -14, y: -16, w: 28, h: 16 }],
    },
    sideHeavy: {
      name: 'Purple Surge',
      startup: 11, active: 8, recovery: 17,
      damage: 19,
      knockback: { base: 33, scaling: 1.12, angle: 30 },
      hitstun: 21, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: 10, y: -64, w: 52, h: 34 }],
    },
    upHeavy: {
      name: 'Smart Launch',
      startup: 10, active: 7, recovery: 15,
      damage: 17,
      knockback: { base: 30, scaling: 1.1, angle: 89 },
      hitstun: 20, isHeavy: true, effect: 'sparkle',
      hitboxes: [{ x: -14, y: -105, w: 32, h: 42 }],
    },
    downHeavy: {
      name: 'Thesis Slam',
      startup: 13, active: 6, recovery: 19,
      damage: 18,
      knockback: { base: 27, scaling: 1.0, angle: 270 },
      hitstun: 19, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -22, y: -10, w: 44, h: 10 }],
    },
    signature: {
      name: 'Spec Flash',
      startup: 15, active: 25, recovery: 20,
      damage: 20,
      knockback: { base: 36, scaling: 1.15, angle: 10 },
      hitstun: 22, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: 20, y: -75, w: 100, h: 25 }],
    },
    sigSide: {
      name: 'Spec Flash',
      startup: 15, active: 25, recovery: 20,
      damage: 20,
      knockback: { base: 36, scaling: 1.15, angle: 10 },
      hitstun: 22, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: 20, y: -75, w: 100, h: 25 }],
    },
    sigNeutral: {
      name: 'Logic Loop',
      startup: 5, active: 11, recovery: 14,
      damage: 18,
      knockback: { base: 30, scaling: 1.0, angle: 70 },
      hitstun: 20, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: -32, y: -88, w: 64, h: 78 }],
    },
    sigDown: {
      name: 'Code Crash',
      startup: 10, active: 6, recovery: 18,
      damage: 20,
      knockback: { base: 26, scaling: 1.05, angle: 275 },
      hitstun: 20, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: -16, y: -20, w: 32, h: 20 }],
    },
  },
};
