export default {
  name: 'Ajay',
  palette: {
    skin: '#7B4A2D',
    hair: '#100808',
    eye: '#3A1A0A',
    outfit1: '#CC2222',  // red flannel
    outfit2: '#3A5CB5',  // blue jeans
    shoes: '#F5F5F5',    // Air Force 1s
    aura: '#DC143C',
  },
  features: {
    hairStyle: 'wavy',
    hasEarrings: false,
    hasChain: false,
    hasGlasses: false,
    hasBandana: false,
    hasNoseRing: false,
  },
  proportions: { weight: 96, height: 1.0, width: 1.0 },
  stats: { speed: 1.1, jump: 1.0, air: 1.05, fall: 1.0 },
  moves: {
    neutralLight: {
      name: 'Wavy Jab',
      startup: 3, active: 3, recovery: 6,
      damage: 6,
      knockback: { base: 9, scaling: 0.32, angle: 40 },
      hitstun: 12, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 20, y: -62, w: 28, h: 18 }],
    },
    sideLight: {
      name: 'Flannel Flap',
      startup: 5, active: 6, recovery: 9,
      damage: 9,
      knockback: { base: 17, scaling: 0.58, angle: 28 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 14, y: -58, w: 42, h: 26 }],
    },
    upLight: {
      name: 'Hair Toss',
      startup: 4, active: 5, recovery: 8,
      damage: 8,
      knockback: { base: 19, scaling: 0.65, angle: 80 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -10, y: -88, w: 28, h: 28 }],
    },
    downLight: {
      name: 'AF1 Slide',
      startup: 5, active: 4, recovery: 9,
      damage: 7,
      knockback: { base: 12, scaling: 0.48, angle: 270 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 10, y: -14, w: 34, h: 14 }],
    },
    neutralAir: {
      name: 'Open Flannel',
      startup: 4, active: 8, recovery: 10,
      damage: 8,
      knockback: { base: 15, scaling: 0.5, angle: 45 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -20, y: -62, w: 46, h: 40 }],
    },
    forwardAir: {
      name: 'Denim Drive',
      startup: 5, active: 5, recovery: 8,
      damage: 10,
      knockback: { base: 21, scaling: 0.68, angle: 28 },
      hitstun: 16, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 22, y: -56, w: 34, h: 24 }],
    },
    backAir: {
      name: 'Heel Kick',
      startup: 6, active: 5, recovery: 9,
      damage: 12,
      knockback: { base: 25, scaling: 0.76, angle: 148 },
      hitstun: 17, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -34, y: -44, w: 30, h: 20 }],
    },
    upAir: {
      name: 'Crown Punch',
      startup: 4, active: 6, recovery: 8,
      damage: 9,
      knockback: { base: 21, scaling: 0.66, angle: 85 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -10, y: -96, w: 24, h: 20 }],
    },
    downAir: {
      name: 'Plaid Stomp',
      startup: 8, active: 4, recovery: 12,
      damage: 13,
      knockback: { base: 17, scaling: 0.78, angle: 270 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -14, y: -16, w: 28, h: 16 }],
    },
    sideHeavy: {
      name: 'Flannel Slam',
      startup: 11, active: 8, recovery: 18,
      damage: 20,
      knockback: { base: 34, scaling: 1.15, angle: 30 },
      hitstun: 22, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: 10, y: -65, w: 56, h: 36 }],
    },
    upHeavy: {
      name: 'Jeans Launch',
      startup: 10, active: 7, recovery: 15,
      damage: 18,
      knockback: { base: 30, scaling: 1.08, angle: 88 },
      hitstun: 20, isHeavy: true, effect: 'punch',
      hitboxes: [{ x: -14, y: -102, w: 34, h: 42 }],
    },
    downHeavy: {
      name: 'Air Force Quake',
      startup: 13, active: 6, recovery: 19,
      damage: 19,
      knockback: { base: 27, scaling: 1.0, angle: 270 },
      hitstun: 20, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -24, y: -10, w: 48, h: 10 }],
    },
    signature: {
      name: 'Flannel Fury',
      startup: 8, active: 20, recovery: 18,
      damage: 8,       // per hit, 3 pulses; final hit is stronger
      knockback: { base: 15, scaling: 0.5, angle: 20 },
      hitstun: 14, isHeavy: true, isSig: true, isMultiHit: true, effect: 'slash',
      hitCount: 3,
      finalHitKnockback: { base: 35, scaling: 1.2, angle: 20 },
      hitboxes: [{ x: -5, y: -80, w: 65, h: 75 }],
    },
  },
};
