export default {
  name: 'Arthur',
  palette: {
    skin: '#E8C5A0',         // light skin
    hair: '#B8895A',         // dirty blonde / light brown
    eye: '#6B4A2A',
    outfit1: '#2A2E36',      // dark gray zip hoodie
    outfit2: '#1A2440',      // navy cargo pants
    shoes: '#1F2438',        // navy Dunks
    shoesAccent: '#F5F5F5',  // white panel
    undertop: '#E8E8E8',     // light tee peek
    chain: '#C8C8C8',        // silver chain
    aura: '#00BFFF',
  },
  features: {
    hairStyle: 'straight_bangs',
    hoodieStyle: 'zip',
    hasHoodUp: true,
    hasUndershirt: true,
    hasPantChain: true,
    hasEarrings: false,
    hasChain: false,
    hasGlasses: false,
    hasBandana: false,
    hasNoseRing: false,
    shoeStyle: 'nike_dunk',
  },
  proportions: { weight: 88, height: 1.0, width: 0.95 },
  stats: { speed: 1.05, jump: 1.1, air: 1.15, fall: 0.9 },
  moves: {
    neutralLight: {
      name: 'Hoodie Flick',
      startup: 3, active: 3, recovery: 7,
      damage: 5,
      knockback: { base: 7, scaling: 0.28, angle: 40 },
      hitstun: 11, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 18, y: -62, w: 28, h: 18 }],
    },
    sideLight: {
      name: 'Skate Kick',
      startup: 5, active: 5, recovery: 9,
      damage: 8,
      knockback: { base: 16, scaling: 0.55, angle: 28 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 14, y: -40, w: 38, h: 22 }],
    },
    upLight: {
      name: 'Bangs Swipe',
      startup: 4, active: 5, recovery: 8,
      damage: 7,
      knockback: { base: 18, scaling: 0.6, angle: 82 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -8, y: -88, w: 28, h: 28 }],
    },
    downLight: {
      name: 'Low Slide',
      startup: 6, active: 4, recovery: 8,
      damage: 6,
      knockback: { base: 10, scaling: 0.45, angle: 270 },
      hitstun: 12, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 8, y: -12, w: 32, h: 12 }],
    },
    neutralAir: {
      name: 'Float Kick',
      startup: 4, active: 9, recovery: 9,
      damage: 8,
      knockback: { base: 14, scaling: 0.48, angle: 50 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -18, y: -55, w: 42, h: 38 }],
    },
    forwardAir: {
      name: 'Air Stab',
      startup: 4, active: 5, recovery: 7,
      damage: 9,
      knockback: { base: 20, scaling: 0.65, angle: 25 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 22, y: -58, w: 32, h: 22 }],
    },
    backAir: {
      name: 'Board Smack',
      startup: 6, active: 5, recovery: 8,
      damage: 11,
      knockback: { base: 24, scaling: 0.72, angle: 145 },
      hitstun: 17, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -32, y: -48, w: 28, h: 22 }],
    },
    upAir: {
      name: 'Flip Up',
      startup: 4, active: 7, recovery: 7,
      damage: 9,
      knockback: { base: 19, scaling: 0.62, angle: 88 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -12, y: -98, w: 26, h: 22 }],
    },
    downAir: {
      name: 'Drop Kick',
      startup: 8, active: 5, recovery: 11,
      damage: 13,
      knockback: { base: 16, scaling: 0.75, angle: 270 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -14, y: -18, w: 28, h: 18 }],
    },
    sideHeavy: {
      name: 'Hoodie Cannon',
      startup: 11, active: 7, recovery: 16,
      damage: 18,
      knockback: { base: 32, scaling: 1.1, angle: 30 },
      hitstun: 20, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: 12, y: -62, w: 50, h: 32 }],
    },
    upHeavy: {
      name: 'Rising Slam',
      startup: 10, active: 8, recovery: 14,
      damage: 16,
      knockback: { base: 28, scaling: 1.05, angle: 90 },
      hitstun: 19, isHeavy: true, effect: 'punch',
      hitboxes: [{ x: -14, y: -105, w: 32, h: 42 }],
    },
    downHeavy: {
      name: 'Grind Press',
      startup: 13, active: 6, recovery: 18,
      damage: 18,
      knockback: { base: 26, scaling: 0.98, angle: 270 },
      hitstun: 19, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -22, y: -10, w: 44, h: 10 }],
    },
    signature: {
      name: 'Peace Blast',
      startup: 10, active: 30, recovery: 18,
      damage: 22,
      knockback: { base: 38, scaling: 1.3, angle: 15 },
      hitstun: 23, isHeavy: true, isSig: true, isProjectile: true, effect: 'sparkle',
      hitboxes: [{ x: 30, y: -60, w: 80, h: 20 }],
      momentum: { x: 0, y: 0 },
    },
    sigSide: {
      name: 'Peace Blast',
      startup: 10, active: 30, recovery: 18,
      damage: 22,
      knockback: { base: 38, scaling: 1.3, angle: 15 },
      hitstun: 23, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: 30, y: -60, w: 80, h: 20 }],
    },
    sigNeutral: {
      name: 'Board Pop',
      startup: 7, active: 14, recovery: 16,
      damage: 20,
      knockback: { base: 34, scaling: 1.12, angle: 82 },
      hitstun: 21, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: -22, y: -108, w: 44, h: 44 }],
    },
    sigDown: {
      name: 'Grind Spike',
      startup: 9, active: 7, recovery: 16,
      damage: 19,
      knockback: { base: 24, scaling: 1.0, angle: 278 },
      hitstun: 19, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: -15, y: -14, w: 30, h: 14 }],
    },
  },
};
