export default {
  name: 'Cameron',
  palette: {
    skin: '#C19A6B',
    hair: '#1A1008',
    eye: '#4A3020',
    outfit1: '#AAAAAA',  // heather gray SANTOS hoodie
    outfit2: '#111111',  // black track pants
    shoes: '#CCCCCC',    // gray Nike Dunks
    aura: '#20B2AA',
  },
  features: {
    hairStyle: 'medium_sweep',
    hasEarrings: false,
    hasChain: false,
    hasGlasses: false,
    hasBandana: false,
    hasNoseRing: false,
  },
  proportions: { weight: 94, height: 1.0, width: 1.0 },
  stats: { speed: 1.05, jump: 1.15, air: 1.05, fall: 1.05 },
  moves: {
    neutralLight: {
      name: 'Santos Jab',
      startup: 3, active: 3, recovery: 6,
      damage: 6,
      knockback: { base: 9, scaling: 0.33, angle: 42 },
      hitstun: 12, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 20, y: -60, w: 28, h: 18 }],
    },
    sideLight: {
      name: 'Track Sweep',
      startup: 5, active: 5, recovery: 9,
      damage: 9,
      knockback: { base: 17, scaling: 0.57, angle: 30 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 14, y: -50, w: 40, h: 24 }],
    },
    upLight: {
      name: 'Happy Uppercut',
      startup: 4, active: 6, recovery: 8,
      damage: 8,
      knockback: { base: 20, scaling: 0.68, angle: 82 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -8, y: -90, w: 28, h: 30 }],
    },
    downLight: {
      name: 'Dunk Kick',
      startup: 5, active: 4, recovery: 9,
      damage: 7,
      knockback: { base: 12, scaling: 0.46, angle: 270 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 10, y: -14, w: 34, h: 14 }],
    },
    neutralAir: {
      name: 'Hype Spin',
      startup: 4, active: 8, recovery: 10,
      damage: 8,
      knockback: { base: 15, scaling: 0.5, angle: 46 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -20, y: -60, w: 44, h: 40 }],
    },
    forwardAir: {
      name: 'Air High-Five',
      startup: 5, active: 5, recovery: 8,
      damage: 10,
      knockback: { base: 22, scaling: 0.7, angle: 28 },
      hitstun: 16, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 20, y: -56, w: 34, h: 24 }],
    },
    backAir: {
      name: 'Back Heel',
      startup: 6, active: 4, recovery: 9,
      damage: 11,
      knockback: { base: 24, scaling: 0.74, angle: 150 },
      hitstun: 17, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -34, y: -44, w: 30, h: 20 }],
    },
    upAir: {
      name: 'Teal Flip',
      startup: 5, active: 6, recovery: 8,
      damage: 9,
      knockback: { base: 20, scaling: 0.65, angle: 86 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -10, y: -96, w: 24, h: 20 }],
    },
    downAir: {
      name: 'Dunk Stamp',
      startup: 8, active: 5, recovery: 12,
      damage: 14,
      knockback: { base: 18, scaling: 0.8, angle: 270 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -14, y: -16, w: 28, h: 16 }],
    },
    sideHeavy: {
      name: 'Hoodie Charge',
      startup: 12, active: 8, recovery: 18,
      damage: 20,
      knockback: { base: 34, scaling: 1.18, angle: 32 },
      hitstun: 22, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: 10, y: -65, w: 54, h: 35 }],
    },
    upHeavy: {
      name: 'Launch Pad',
      startup: 10, active: 8, recovery: 15,
      damage: 17,
      knockback: { base: 30, scaling: 1.12, angle: 90 },
      hitstun: 20, isHeavy: true, effect: 'punch',
      hitboxes: [{ x: -14, y: -105, w: 34, h: 42 }],
    },
    downHeavy: {
      name: 'Ground Smash',
      startup: 14, active: 6, recovery: 20,
      damage: 19,
      knockback: { base: 28, scaling: 1.02, angle: 270 },
      hitstun: 20, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -24, y: -10, w: 48, h: 10 }],
    },
    signature: {
      name: 'Cam Slam',
      startup: 12, active: 18, recovery: 22,
      damage: 28,
      knockback: { base: 44, scaling: 1.5, angle: 270 },
      hitstun: 26, isHeavy: true, isSig: true, effect: 'explosion',
      hitboxes: [{ x: -25, y: -20, w: 50, h: 20 }],
      momentum: { x: 0, y: 5 },
    },
  },
};
