export default {
  name: 'Dilion',
  palette: {
    skin: '#E8C2A0',
    hair: '#8B5C2A',         // medium messy brown
    eye: '#5A3A1A',
    outfit1: '#101014',      // black pullover hoodie
    outfit2: '#0A0A0A',      // black cargo pants
    shoes: '#0F0F12',        // black/white Dunks
    shoesAccent: '#F5F5F5',
    undertop: '#F0F0F0',
    chain: '#C8C8C8',        // silver pant chain
    aura: '#FF69B4',
  },
  features: {
    hairStyle: 'long_wavy',
    hoodieStyle: 'pullover',
    hasUndershirt: true,
    hasPantChain: true,
    hasEarrings: false,
    hasChain: false,
    hasGlasses: false,
    hasBandana: false,
    hasNoseRing: false,
    hasBrowPiercing: true,
    shoeStyle: 'nike_dunk',
  },
  proportions: { weight: 85, height: 0.97, width: 0.93 },
  stats: { speed: 1.1, jump: 1.05, air: 1.15, fall: 0.88 },
  moves: {
    neutralLight: {
      name: 'Ring Tap',
      startup: 3, active: 3, recovery: 6,
      damage: 5,
      knockback: { base: 8, scaling: 0.3, angle: 40 },
      hitstun: 11, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: 18, y: -62, w: 26, h: 18 }],
    },
    sideLight: {
      name: 'Cargo Kick',
      startup: 5, active: 5, recovery: 9,
      damage: 8,
      knockback: { base: 16, scaling: 0.54, angle: 28 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 12, y: -44, w: 36, h: 22 }],
    },
    upLight: {
      name: 'Indie Flip',
      startup: 4, active: 5, recovery: 8,
      damage: 7,
      knockback: { base: 18, scaling: 0.62, angle: 82 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -8, y: -88, w: 26, h: 28 }],
    },
    downLight: {
      name: 'Vans Slide',
      startup: 5, active: 4, recovery: 8,
      damage: 6,
      knockback: { base: 10, scaling: 0.44, angle: 270 },
      hitstun: 12, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 8, y: -12, w: 30, h: 12 }],
    },
    neutralAir: {
      name: 'Float Spin',
      startup: 4, active: 9, recovery: 9,
      damage: 8,
      knockback: { base: 14, scaling: 0.48, angle: 48 },
      hitstun: 14, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: -18, y: -58, w: 40, h: 38 }],
    },
    forwardAir: {
      name: 'Pink Drive',
      startup: 5, active: 5, recovery: 8,
      damage: 9,
      knockback: { base: 20, scaling: 0.65, angle: 26 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 20, y: -56, w: 32, h: 22 }],
    },
    backAir: {
      name: 'Band Tee Whip',
      startup: 5, active: 5, recovery: 8,
      damage: 11,
      knockback: { base: 23, scaling: 0.72, angle: 148 },
      hitstun: 16, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -30, y: -46, w: 26, h: 20 }],
    },
    upAir: {
      name: 'Wavy Lift',
      startup: 4, active: 7, recovery: 8,
      damage: 9,
      knockback: { base: 19, scaling: 0.64, angle: 87 },
      hitstun: 15, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: -10, y: -96, w: 22, h: 20 }],
    },
    downAir: {
      name: 'Cargo Drop',
      startup: 8, active: 5, recovery: 11,
      damage: 12,
      knockback: { base: 15, scaling: 0.72, angle: 270 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -12, y: -16, w: 24, h: 16 }],
    },
    sideHeavy: {
      name: 'Khaki Cannon',
      startup: 11, active: 7, recovery: 17,
      damage: 19,
      knockback: { base: 32, scaling: 1.1, angle: 28 },
      hitstun: 21, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: 10, y: -62, w: 50, h: 32 }],
    },
    upHeavy: {
      name: 'Pink Rise',
      startup: 10, active: 7, recovery: 15,
      damage: 17,
      knockback: { base: 28, scaling: 1.06, angle: 90 },
      hitstun: 19, isHeavy: true, effect: 'sparkle',
      hitboxes: [{ x: -12, y: -104, w: 30, h: 42 }],
    },
    downHeavy: {
      name: 'Indie Crash',
      startup: 13, active: 6, recovery: 18,
      damage: 18,
      knockback: { base: 26, scaling: 0.98, angle: 270 },
      hitstun: 19, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -20, y: -10, w: 40, h: 10 }],
    },
    signature: {
      name: 'Ring Toss',
      startup: 10, active: 50, recovery: 20,
      damage: 16,
      knockback: { base: 34, scaling: 1.15, angle: 35 },
      hitstun: 20, isHeavy: true, isSig: true, isProjectile: true, effect: 'sparkle',
      hitboxes: [{ x: 25, y: -65, w: 35, h: 20 }],
    },
    sigSide: {
      name: 'Ring Toss',
      startup: 10, active: 50, recovery: 20,
      damage: 16,
      knockback: { base: 34, scaling: 1.15, angle: 35 },
      hitstun: 20, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: 25, y: -65, w: 35, h: 20 }],
    },
    sigNeutral: {
      name: 'Indie Blast',
      startup: 5, active: 11, recovery: 13,
      damage: 19,
      knockback: { base: 30, scaling: 1.06, angle: 60 },
      hitstun: 19, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: -28, y: -82, w: 56, h: 72 }],
    },
    sigDown: {
      name: 'Vans Stomp',
      startup: 10, active: 6, recovery: 17,
      damage: 21,
      knockback: { base: 26, scaling: 1.02, angle: 275 },
      hitstun: 20, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: -14, y: -12, w: 28, h: 12 }],
    },
  },
};
