export default {
  name: 'Harshith',
  palette: {
    skin: '#A06A45',         // tan brown skin
    hair: '#0A0A0A',
    eye: '#2A1A0A',
    outfit1: '#0F0F12',      // black oversized hoodie
    outfit2: '#0A0A0A',      // black pants
    shoes: '#0F0F12',        // black Dunks
    shoesAccent: '#F5F5F5',
    undertop: '#F0F0F0',
    bandana1: '#0A0A0A',
    bandana2: '#FFFFFF',
    chain: '#C8C8C8',        // silver pant chain
    facialHair: '#0A0A0A',
    accent: '#C8C8C8',
    aura: '#FFD700',
  },
  features: {
    hairStyle: 'short_messy',
    hoodieStyle: 'pullover',
    hasUndershirt: true,
    hasPantChain: true,
    hasMustache: true,
    hasGoatee: true,
    hasEarrings: true,
    hasChain: false,
    hasGlasses: false,
    hasBandana: true,
    hasNoseRing: false,
    shoeStyle: 'nike_dunk',
  },
  proportions: { weight: 112, height: 1.05, width: 1.12 },
  stats: { speed: 0.95, jump: 0.95, air: 0.95, fall: 1.2 },
  moves: {
    neutralLight: {
      name: 'Gold Jab',
      startup: 4, active: 3, recovery: 8,
      damage: 7,
      knockback: { base: 10, scaling: 0.38, angle: 40 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 22, y: -62, w: 30, h: 20 }],
    },
    sideLight: {
      name: 'Timb Kick',
      startup: 6, active: 5, recovery: 11,
      damage: 11,
      knockback: { base: 20, scaling: 0.68, angle: 28 },
      hitstun: 17, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 16, y: -40, w: 44, h: 28 }],
    },
    upLight: {
      name: 'Bandana Whip',
      startup: 5, active: 6, recovery: 9,
      damage: 9,
      knockback: { base: 22, scaling: 0.7, angle: 80 },
      hitstun: 15, isHeavy: false, effect: 'slash',
      hitboxes: [{ x: -8, y: -92, w: 32, h: 30 }],
    },
    downLight: {
      name: 'Chain Drag',
      startup: 6, active: 4, recovery: 10,
      damage: 8,
      knockback: { base: 14, scaling: 0.54, angle: 270 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 12, y: -14, w: 36, h: 14 }],
    },
    neutralAir: {
      name: 'Hoodie Spread',
      startup: 5, active: 7, recovery: 11,
      damage: 9,
      knockback: { base: 16, scaling: 0.54, angle: 46 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -22, y: -65, w: 48, h: 44 }],
    },
    forwardAir: {
      name: 'Chain Forward',
      startup: 6, active: 5, recovery: 10,
      damage: 11,
      knockback: { base: 24, scaling: 0.78, angle: 28 },
      hitstun: 17, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 18, y: -58, w: 38, h: 26 }],
    },
    backAir: {
      name: 'Timb Reverse',
      startup: 7, active: 4, recovery: 10,
      damage: 13,
      knockback: { base: 27, scaling: 0.84, angle: 148 },
      hitstun: 18, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -38, y: -42, w: 32, h: 22 }],
    },
    upAir: {
      name: 'Gold Ascend',
      startup: 5, active: 6, recovery: 9,
      damage: 10,
      knockback: { base: 22, scaling: 0.7, angle: 86 },
      hitstun: 16, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -10, y: -98, w: 26, h: 22 }],
    },
    downAir: {
      name: 'Boot Spike',
      startup: 9, active: 4, recovery: 13,
      damage: 16,
      knockback: { base: 22, scaling: 0.9, angle: 270 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -16, y: -16, w: 32, h: 16 }],
    },
    sideHeavy: {
      name: 'Chain Whip',
      startup: 13, active: 9, recovery: 21,
      damage: 23,
      knockback: { base: 38, scaling: 1.32, angle: 32 },
      hitstun: 24, isHeavy: true, effect: 'slash',
      hitboxes: [{ x: 12, y: -68, w: 60, h: 40 }],
    },
    upHeavy: {
      name: 'Street Lift',
      startup: 12, active: 8, recovery: 18,
      damage: 20,
      knockback: { base: 34, scaling: 1.18, angle: 88 },
      hitstun: 22, isHeavy: true, effect: 'punch',
      hitboxes: [{ x: -16, y: -110, w: 36, h: 46 }],
    },
    downHeavy: {
      name: 'Timb Quake',
      startup: 16, active: 7, recovery: 24,
      damage: 22,
      knockback: { base: 32, scaling: 1.08, angle: 270 },
      hitstun: 22, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -30, y: -10, w: 60, h: 10 }],
    },
    signature: {
      name: 'Bandana Boomerang',
      startup: 8, active: 40, recovery: 22,
      damage: 18,
      knockback: { base: 35, scaling: 1.2, angle: 25 },
      hitstun: 20, isHeavy: true, isSig: true, effect: 'slash',
      hitboxes: [{ x: 25, y: -65, w: 40, h: 20 }],
    },
    sigSide: {
      name: 'Bandana Boomerang',
      startup: 8, active: 40, recovery: 22,
      damage: 18,
      knockback: { base: 35, scaling: 1.2, angle: 25 },
      hitstun: 20, isHeavy: true, isSig: true, effect: 'slash',
      hitboxes: [{ x: 25, y: -65, w: 40, h: 20 }],
    },
    sigNeutral: {
      name: 'Gold Slam',
      startup: 14, active: 10, recovery: 24,
      damage: 30,
      knockback: { base: 44, scaling: 1.4, angle: 80 },
      hitstun: 28, isHeavy: true, isSig: true, effect: 'explosion',
      hitboxes: [{ x: -42, y: -96, w: 84, h: 86 }],
    },
    sigDown: {
      name: 'Timb Quake',
      startup: 18, active: 10, recovery: 28,
      damage: 33,
      knockback: { base: 42, scaling: 1.38, angle: 265 },
      hitstun: 28, isHeavy: true, isSig: true, effect: 'explosion',
      hitboxes: [{ x: -54, y: -12, w: 108, h: 12 }],
    },
  },
};
