export default {
  name: 'Mathew',
  palette: {
    skin: '#B58660',
    hair: '#3A2010',         // dark brown
    eye: '#3A2510',
    outfit1: '#1F4ED8',      // royal blue Nike hoodie
    outfit2: '#0A0A0A',      // black cargo pants
    shoes: '#1F4ED8',        // blue Dunks
    shoesAccent: '#F5F5F5',
    chain: '#C8C8C8',
    accent: '#FFFFFF',       // Nike swoosh
    aura: '#1F4ED8',
  },
  features: {
    hairStyle: 'spiky_brown',
    hoodieStyle: 'pullover',
    hasUndershirt: false,
    hasPantChain: true,
    hasHoodieLogo: true,
    hasSmile: true,
    hasEarrings: false,
    hasChain: false,
    hasGlasses: false,
    hasBandana: false,
    hasNoseRing: false,
    shoeStyle: 'nike_dunk',
  },
  proportions: { weight: 82, height: 0.92, width: 0.9 },
  stats: { speed: 1.2, jump: 1.1, air: 1.2, fall: 1.0 },
  moves: {
    neutralLight: {
      name: 'Mohawk Jab',
      startup: 2, active: 3, recovery: 5,
      damage: 5,
      knockback: { base: 8, scaling: 0.28, angle: 44 },
      hitstun: 11, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 18, y: -62, w: 26, h: 18 }],
    },
    sideLight: {
      name: 'Air Max Kick',
      startup: 4, active: 4, recovery: 8,
      damage: 8,
      knockback: { base: 15, scaling: 0.52, angle: 30 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 12, y: -40, w: 36, h: 22 }],
    },
    upLight: {
      name: 'Spike Pop',
      startup: 3, active: 5, recovery: 7,
      damage: 7,
      knockback: { base: 18, scaling: 0.6, angle: 82 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -8, y: -90, w: 26, h: 28 }],
    },
    downLight: {
      name: 'Quick Low',
      startup: 4, active: 3, recovery: 7,
      damage: 6,
      knockback: { base: 10, scaling: 0.42, angle: 270 },
      hitstun: 12, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 8, y: -12, w: 30, h: 12 }],
    },
    neutralAir: {
      name: 'Wild Spin',
      startup: 3, active: 9, recovery: 9,
      damage: 8,
      knockback: { base: 14, scaling: 0.48, angle: 46 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -18, y: -58, w: 40, h: 38 }],
    },
    forwardAir: {
      name: 'Yellow Dash',
      startup: 4, active: 5, recovery: 7,
      damage: 9,
      knockback: { base: 20, scaling: 0.65, angle: 26 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 20, y: -56, w: 32, h: 22 }],
    },
    backAir: {
      name: 'Neon Heel',
      startup: 5, active: 4, recovery: 8,
      damage: 11,
      knockback: { base: 23, scaling: 0.72, angle: 148 },
      hitstun: 16, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -30, y: -42, w: 26, h: 18 }],
    },
    upAir: {
      name: 'Hawk Flip',
      startup: 3, active: 6, recovery: 7,
      damage: 9,
      knockback: { base: 19, scaling: 0.63, angle: 88 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -8, y: -96, w: 22, h: 20 }],
    },
    downAir: {
      name: 'Neon Spike',
      startup: 7, active: 5, recovery: 10,
      damage: 12,
      knockback: { base: 16, scaling: 0.72, angle: 270 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -12, y: -16, w: 24, h: 16 }],
    },
    sideHeavy: {
      name: 'Turbo Rush',
      startup: 10, active: 7, recovery: 16,
      damage: 18,
      knockback: { base: 32, scaling: 1.1, angle: 28 },
      hitstun: 20, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: 10, y: -62, w: 50, h: 32 }],
    },
    upHeavy: {
      name: 'Hawk Ascent',
      startup: 9, active: 8, recovery: 14,
      damage: 16,
      knockback: { base: 28, scaling: 1.05, angle: 90 },
      hitstun: 19, isHeavy: true, effect: 'punch',
      hitboxes: [{ x: -12, y: -105, w: 30, h: 42 }],
    },
    downHeavy: {
      name: 'Crater Stomp',
      startup: 12, active: 6, recovery: 18,
      damage: 17,
      knockback: { base: 26, scaling: 0.98, angle: 270 },
      hitstun: 19, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -20, y: -10, w: 40, h: 10 }],
    },
    signature: {
      name: 'Spiky Missile',
      startup: 5, active: 20, recovery: 18,
      damage: 22,
      knockback: { base: 40, scaling: 1.3, angle: 20 },
      hitstun: 24, isHeavy: true, isSig: true, effect: 'explosion',
      hitboxes: [{ x: 10, y: -85, w: 65, h: 75 }],
      momentum: { x: 7, y: -3 },
    },
    sigSide: {
      name: 'Spiky Missile',
      startup: 5, active: 20, recovery: 18,
      damage: 22,
      knockback: { base: 40, scaling: 1.3, angle: 20 },
      hitstun: 24, isHeavy: true, isSig: true, effect: 'explosion',
      hitboxes: [{ x: 10, y: -85, w: 65, h: 75 }],
      momentum: { x: 7, y: -3 },
    },
    sigNeutral: {
      name: 'Neon Burst',
      startup: 4, active: 9, recovery: 14,
      damage: 19,
      knockback: { base: 32, scaling: 1.1, angle: 60 },
      hitstun: 19, isHeavy: true, isSig: true, effect: 'explosion',
      hitboxes: [{ x: -32, y: -92, w: 64, h: 82 }],
    },
    sigDown: {
      name: 'Hawk Dive',
      startup: 7, active: 6, recovery: 14,
      damage: 21,
      knockback: { base: 28, scaling: 1.06, angle: 270 },
      hitstun: 20, isHeavy: true, isSig: true, effect: 'explosion',
      hitboxes: [{ x: -17, y: -14, w: 34, h: 14 }],
    },
  },
};
