export default {
  name: 'Matteen',
  palette: {
    skin: '#B57A52',         // warm tan brown
    hair: '#0A0A0A',
    eye: '#3A2510',
    outfit1: '#0F0F12',      // black Stussy hoodie
    outfit2: '#0A0A0A',      // black cargo pants
    shoes: '#0F0F12',        // black Nike Dunk uppers
    shoesAccent: '#F5F5F5',  // white panel
    undertop: '#F5F5F5',     // white tee peek
    chain: '#C8C8C8',        // silver pant chain
    accent: '#FF3030',
    aura: '#FF3030',
  },
  features: {
    hairStyle: 'spiky_natural',
    hoodieStyle: 'pullover',
    hasUndershirt: true,
    hasPantChain: true,
    hasHoodieLogo: true,
    hasEarrings: false,
    hasChain: false,
    hasGlasses: false,
    hasBandana: false,
    hasNoseRing: false,
    shoeStyle: 'nike_dunk',
  },
  proportions: { weight: 108, height: 1.05, width: 1.1 },
  stats: { speed: 1.0, jump: 0.95, air: 0.95, fall: 1.15 },
  moves: {
    neutralLight: {
      name: 'Spike Poke',
      startup: 4, active: 3, recovery: 7,
      damage: 7,
      knockback: { base: 10, scaling: 0.38, angle: 42 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 22, y: -62, w: 28, h: 18 }],
    },
    sideLight: {
      name: 'Boot Stomp',
      startup: 6, active: 5, recovery: 11,
      damage: 11,
      knockback: { base: 20, scaling: 0.68, angle: 25 },
      hitstun: 17, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 16, y: -38, w: 42, h: 28 }],
    },
    upLight: {
      name: 'Spike Headbutt',
      startup: 5, active: 5, recovery: 9,
      damage: 9,
      knockback: { base: 22, scaling: 0.72, angle: 78 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -8, y: -92, w: 30, h: 28 }],
    },
    downLight: {
      name: 'Boot Scrape',
      startup: 6, active: 4, recovery: 10,
      damage: 8,
      knockback: { base: 14, scaling: 0.55, angle: 270 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 12, y: -14, w: 36, h: 14 }],
    },
    neutralAir: {
      name: 'Jacket Spin',
      startup: 5, active: 7, recovery: 11,
      damage: 9,
      knockback: { base: 16, scaling: 0.55, angle: 45 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -22, y: -65, w: 48, h: 42 }],
    },
    forwardAir: {
      name: 'Flying Elbow',
      startup: 6, active: 5, recovery: 9,
      damage: 11,
      knockback: { base: 24, scaling: 0.78, angle: 28 },
      hitstun: 17, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 18, y: -58, w: 38, h: 26 }],
    },
    backAir: {
      name: 'Rear Boot',
      startup: 7, active: 4, recovery: 10,
      damage: 12,
      knockback: { base: 26, scaling: 0.82, angle: 148 },
      hitstun: 18, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -36, y: -42, w: 32, h: 22 }],
    },
    upAir: {
      name: 'Rising Spike',
      startup: 5, active: 6, recovery: 9,
      damage: 10,
      knockback: { base: 22, scaling: 0.7, angle: 86 },
      hitstun: 16, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -10, y: -98, w: 26, h: 22 }],
    },
    downAir: {
      name: 'Heavy Drop',
      startup: 9, active: 4, recovery: 13,
      damage: 15,
      knockback: { base: 20, scaling: 0.88, angle: 270 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -16, y: -16, w: 32, h: 16 }],
    },
    sideHeavy: {
      name: 'Jacket Crusher',
      startup: 13, active: 9, recovery: 20,
      damage: 23,
      knockback: { base: 38, scaling: 1.3, angle: 32 },
      hitstun: 24, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: 12, y: -68, w: 58, h: 38 }],
    },
    upHeavy: {
      name: 'Spike Launch',
      startup: 11, active: 8, recovery: 17,
      damage: 20,
      knockback: { base: 34, scaling: 1.18, angle: 88 },
      hitstun: 22, isHeavy: true, effect: 'punch',
      hitboxes: [{ x: -16, y: -108, w: 36, h: 44 }],
    },
    downHeavy: {
      name: 'Boot Quake',
      startup: 15, active: 7, recovery: 22,
      damage: 21,
      knockback: { base: 30, scaling: 1.05, angle: 270 },
      hitstun: 21, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -28, y: -10, w: 56, h: 10 }],
    },
    signature: {
      name: 'Leather Rush',
      startup: 6, active: 18, recovery: 20,
      damage: 26,
      knockback: { base: 40, scaling: 1.35, angle: 25 },
      hitstun: 26, isHeavy: true, isSig: true, effect: 'explosion',
      hitboxes: [{ x: 5, y: -80, w: 60, h: 75 }],
      momentum: { x: 5, y: -2 },
    },
  },
};
