export default {
  name: 'Pratik',
  palette: {
    skin: '#A57350',
    hair: '#0A0A0A',
    eye: '#3A1A0A',
    outfit1: '#1A1A1E',      // plain black tee
    outfit2: '#0A0A0A',      // black cargo pants
    shoes: '#0F0F12',        // black Dunks
    shoesAccent: '#F5F5F5',
    chain: '#C8C8C8',        // silver pant chain
    aura: '#39FF14',
  },
  features: {
    hairStyle: 'spiky_natural',
    hoodieStyle: 'tee',
    hasUndershirt: false,
    hasPantChain: true,
    hasEarrings: true,
    hasChain: false,
    hasGlasses: false,
    hasBandana: false,
    hasNoseRing: false,
    shoeStyle: 'nike_dunk',
  },
  proportions: { weight: 95, height: 1.0, width: 1.0 },
  stats: { speed: 1.1, jump: 1.05, air: 1.0, fall: 1.0 },
  moves: {
    neutralLight: {
      name: 'NB Poke',
      startup: 3, active: 3, recovery: 6,
      damage: 6,
      knockback: { base: 9, scaling: 0.32, angle: 42 },
      hitstun: 12, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 20, y: -62, w: 28, h: 18 }],
    },
    sideLight: {
      name: 'Baggy Kick',
      startup: 5, active: 5, recovery: 9,
      damage: 9,
      knockback: { base: 17, scaling: 0.57, angle: 28 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 14, y: -46, w: 40, h: 24 }],
    },
    upLight: {
      name: 'Earring Flick',
      startup: 4, active: 5, recovery: 8,
      damage: 7,
      knockback: { base: 18, scaling: 0.62, angle: 80 },
      hitstun: 13, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: -8, y: -90, w: 28, h: 28 }],
    },
    downLight: {
      name: 'Jeans Shuffle',
      startup: 5, active: 4, recovery: 9,
      damage: 7,
      knockback: { base: 12, scaling: 0.46, angle: 270 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 10, y: -14, w: 34, h: 14 }],
    },
    neutralAir: {
      name: 'Vintage Spin',
      startup: 4, active: 8, recovery: 10,
      damage: 8,
      knockback: { base: 15, scaling: 0.5, angle: 46 },
      hitstun: 14, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: -20, y: -60, w: 44, h: 40 }],
    },
    forwardAir: {
      name: 'Green Rush',
      startup: 5, active: 5, recovery: 8,
      damage: 10,
      knockback: { base: 21, scaling: 0.68, angle: 28 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 20, y: -56, w: 34, h: 24 }],
    },
    backAir: {
      name: 'Fade Kick',
      startup: 6, active: 4, recovery: 9,
      damage: 11,
      knockback: { base: 24, scaling: 0.74, angle: 150 },
      hitstun: 16, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -34, y: -44, w: 30, h: 20 }],
    },
    upAir: {
      name: 'Neon Launch',
      startup: 5, active: 6, recovery: 8,
      damage: 9,
      knockback: { base: 20, scaling: 0.65, angle: 86 },
      hitstun: 15, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: -10, y: -96, w: 24, h: 20 }],
    },
    downAir: {
      name: 'Bass Drop',
      startup: 9, active: 4, recovery: 12,
      damage: 14,
      knockback: { base: 18, scaling: 0.8, angle: 270 },
      hitstun: 14, isHeavy: false, effect: 'sparkle',
      hitboxes: [{ x: -14, y: -16, w: 28, h: 16 }],
    },
    sideHeavy: {
      name: 'Street Smash',
      startup: 11, active: 8, recovery: 17,
      damage: 19,
      knockback: { base: 34, scaling: 1.15, angle: 30 },
      hitstun: 21, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: 10, y: -64, w: 54, h: 34 }],
    },
    upHeavy: {
      name: 'Groove Upper',
      startup: 10, active: 7, recovery: 15,
      damage: 17,
      knockback: { base: 30, scaling: 1.1, angle: 88 },
      hitstun: 20, isHeavy: true, effect: 'sparkle',
      hitboxes: [{ x: -14, y: -104, w: 32, h: 42 }],
    },
    downHeavy: {
      name: 'Sub Bass Quake',
      startup: 13, active: 6, recovery: 19,
      damage: 18,
      knockback: { base: 27, scaling: 1.0, angle: 270 },
      hitstun: 19, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -22, y: -10, w: 44, h: 10 }],
    },
    signature: {
      name: 'Drop Beat',
      startup: 10, active: 30, recovery: 20,
      damage: 8,       // per note, 3 notes orbit then detonate
      knockback: { base: 32, scaling: 1.1, angle: 60 },
      hitstun: 18, isHeavy: true, isSig: true, isMultiHit: true, effect: 'sparkle',
      hitCount: 3,
      hitboxes: [{ x: -40, y: -90, w: 80, h: 80 }],
    },
  },
};
