export default {
  name: 'Ram',
  palette: {
    skin: '#A06A40',
    hair: '#0A0A0A',
    eye: '#3A2010',
    outfit1: '#101014',      // black pullover hoodie
    outfit2: '#0A0A0A',      // black cargo pants
    shoes: '#0F0F12',        // black Dunks
    shoesAccent: '#F5F5F5',  // white panel
    undertop: '#F5F5F5',     // white tee peek
    chain: '#C8C8C8',        // silver pant chain
    accent: '#FF8C00',
    aura: '#FF8C00',
  },
  features: {
    hairStyle: 'curly',
    hoodieStyle: 'pullover',
    hasUndershirt: true,
    hasPantChain: true,
    hasEarrings: true,
    hasChain: false,
    hasGlasses: false,
    hasBandana: false,
    hasNoseRing: false,
    shoeStyle: 'nike_dunk',
  },
  proportions: { weight: 92, height: 1.0, width: 1.0 },
  stats: { speed: 1.15, jump: 1.05, air: 1.1, fall: 0.95 },
  moves: {
    neutralLight: {
      name: 'Quick Jab',
      startup: 2, active: 3, recovery: 6,
      damage: 5,
      knockback: { base: 8, scaling: 0.3, angle: 45 },
      hitstun: 12, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 20, y: -60, w: 30, h: 20 }],
    },
    sideLight: {
      name: 'Chain Swing',
      startup: 5, active: 5, recovery: 10,
      damage: 9,
      knockback: { base: 18, scaling: 0.6, angle: 30 },
      hitstun: 16, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 15, y: -55, w: 40, h: 25 }],
    },
    upLight: {
      name: 'Hair Flip',
      startup: 4, active: 6, recovery: 8,
      damage: 8,
      knockback: { base: 20, scaling: 0.7, angle: 80 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -10, y: -90, w: 30, h: 30 }],
    },
    downLight: {
      name: 'Leg Sweep',
      startup: 5, active: 4, recovery: 9,
      damage: 7,
      knockback: { base: 12, scaling: 0.5, angle: 270 },
      hitstun: 13, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 10, y: -15, w: 35, h: 15 }],
    },
    neutralAir: {
      name: 'Spin Air',
      startup: 4, active: 8, recovery: 10,
      damage: 8,
      knockback: { base: 15, scaling: 0.5, angle: 45 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -20, y: -60, w: 45, h: 40 }],
    },
    forwardAir: {
      name: 'Air Punch',
      startup: 5, active: 5, recovery: 8,
      damage: 10,
      knockback: { base: 22, scaling: 0.7, angle: 30 },
      hitstun: 16, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: 20, y: -55, w: 35, h: 25 }],
    },
    backAir: {
      name: 'Back Kick',
      startup: 6, active: 4, recovery: 9,
      damage: 11,
      knockback: { base: 25, scaling: 0.75, angle: 150 },
      hitstun: 17, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -35, y: -45, w: 30, h: 20 }],
    },
    upAir: {
      name: 'Headbutt',
      startup: 5, active: 6, recovery: 8,
      damage: 9,
      knockback: { base: 20, scaling: 0.65, angle: 85 },
      hitstun: 15, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -10, y: -95, w: 25, h: 20 }],
    },
    downAir: {
      name: 'Stomp',
      startup: 8, active: 4, recovery: 12,
      damage: 14,
      knockback: { base: 18, scaling: 0.8, angle: 270 },
      hitstun: 14, isHeavy: false, effect: 'punch',
      hitboxes: [{ x: -15, y: -15, w: 30, h: 15 }],
    },
    sideHeavy: {
      name: 'Chain Slam',
      startup: 12, active: 8, recovery: 18,
      damage: 20,
      knockback: { base: 35, scaling: 1.2, angle: 35 },
      hitstun: 22, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: 10, y: -65, w: 55, h: 35 }],
    },
    upHeavy: {
      name: 'Rising Fist',
      startup: 10, active: 7, recovery: 15,
      damage: 17,
      knockback: { base: 30, scaling: 1.1, angle: 88 },
      hitstun: 20, isHeavy: true, effect: 'punch',
      hitboxes: [{ x: -15, y: -100, w: 35, h: 40 }],
    },
    downHeavy: {
      name: 'Ground Pound',
      startup: 14, active: 6, recovery: 20,
      damage: 19,
      knockback: { base: 28, scaling: 1.0, angle: 270 },
      hitstun: 20, isHeavy: true, effect: 'explosion',
      hitboxes: [{ x: -25, y: -10, w: 50, h: 10 }],
    },
    signature: {
      name: 'Curly Whirl',
      startup: 8, active: 22, recovery: 15,
      damage: 24,
      knockback: { base: 42, scaling: 1.4, angle: 50 },
      hitstun: 24, isHeavy: true, isSig: true, effect: 'sparkle',
      hitboxes: [{ x: -35, y: -90, w: 70, h: 80 }],
      momentum: { x: 0, y: -3 },
    },
  },
};
